# Generated by Django 4.2 on 2023-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_deliveries_current_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="package_weight",
            field=models.CharField(max_length=200),
        ),
    ]
